language: node_js
cache: npm

before_install:
- npm i -g npm@6.4.1
- npm install -g @angular/cli
script:
- ng build --prod

before_deploy:
- rm -f dist/one-night-werewolf-ui.tar.gz
- tar czf dist/one-night-werewolf-ui.tar.gz dist/werewolf-ui
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_TOKEN
  file: dist/one-night-werewolf-ui.tar.gz
  skip_cleanup: true
  draft: true
  on:
    repo: aurelien-baudet/one-night-werewolf-ui
